name: Ideation
favicon: null
layout_spectrum: 0.9164565049577504
typography_spectrum: 0.48772402363829315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7837716813664883
  lightness: 0.4658180959522724
  saturation: 0.6807540052104741
  rhythmicContrast: 0.8767809390556067
purpose: []
